stages:
  - build
  - deploy
image: docker:26.1

services:
  - name: docker:26.1-dind
builder:
    stage: build
    script:
        - docker build -t some_local_build:latest .
    except:
        - main
deployer:
    stage: deploy
    script:
        - echo "${CI_REGISTRY_KEY}" | docker login ${CI_REGISTRY} -u json_key --password-stdin
        - >-
          docker build
          "${CI_PROJECT_DIR}"
          --file "${CI_PROJECT_DIR}/Dockerfile"
          --tag "${CI_REGISTRY}/${CI_PROJECT_PATH}/hello:gitlab-${CI_COMMIT_SHORT_SHA}"
        - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH}/hello:gitlab-${CI_COMMIT_SHORT_SHA}"
    only:
        - main